name: Python CI

on:
  push:
    branches: [ main ]     # 当你推送到 main 分支时触发
  pull_request:
    branches: [ main ]     # 当有人发起 PR 时触发

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub 提供的 Linux 环境

    steps:
      # 1️⃣ 拉取你的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 固定版本，避免兼容问题
          cache: 'pip'            # 自动缓存依赖，加快运行速度

      # 3️⃣ 打印 Python 版本（用于确认）
      - name: Check Python version
        run: python -V

      # 4️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5️⃣ 运行测试（pytest）
      - name: Run tests
        run: pytest -q
